cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Anim_Base.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Anim_Directional.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Entity_Manager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/EventManager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_Element.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_Interface.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_Label.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_Manager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_Scrollbar.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/GUI_TextField.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Game.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Main.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Map.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Base.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Collision.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Control.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Movement.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Renderer.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_SheetAnimation.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_Sound.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/S_State.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/SoundManager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/SpriteSheet.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/StateManager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/State_Game.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/State_GameOver.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/State_Intro.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/State_MainMenu.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/State_Paused.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/System_Manager.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio
cpp -LSFML-2.5.0/build-win/lib -o bin/Debug/SFML_c12.exe obj/Debug/Window.o -lsfml-window -lsfml-system -lsfml-graphics -lsfml-audio